# Use Node.js 15 Alpine as base image
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .


RUN npm run build

EXPOSE 4000

CMD ["npm", "start"]
